# HTTP Server port
server:
  port: 8080

spring:
  application:
    name: university-gateway    # Name of the application (used to register service with `eureka`)

archaius:
  configurationSource:
    additionalUrls:

eureka:
  client:
    # This is a eureka server so no need to register
    register-with-eureka: false
    # This is a eureka server so no need to fetch registry
    fetch-registry: false
    # Register url for client
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

  server:
    # Timeout
    wait-time-in-ms-when-sync-empty: 0

zuul:
  # All url come with prefix/api will interpret
  prefix: /api

  routes:
    rest-api-v1:
      path: /v1/**
      url: http://localhost:8081/
