# HTTP Server port
server:
  port: 8080

spring:
  application:
    # Name of the application (used to register service with `eureka`)
    name: university-gateway

  aop:
    proxy-target-class: true

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=university;encrypt=false;loginTimeout=30;
    username: UniversitySA           #spring.datasource.username=sa
    password: 1university@SECRET!    #spring.datasource.password=Admin1234

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        proc:
          param_null_passing: true
        jdbc:
          fetch_size: 100
          batch_size: 50
          batch_versioned_data: true
          lob:
            non_contextual_creation: true

eureka:
  client:
    # This is a eureka server so no need to register
    register-with-eureka: false
    # This is a eureka server so no need to fetch registry
    fetch-registry: false
    # Register url for client
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

  server:
    # Timeout
    wait-time-in-ms-when-sync-empty: 0

zuul:
  # All url come with prefix/api will interpret
  prefix: /api
  routes:
    rest-api-v1:
      path: /v1/**
      url: http://localhost:8081/
