# HTTP Server port
server:
  port: 8081

spring:
  application:
    # Name of the application (used to register service with `eureka`)
    name: university-rest-api

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=university;encrypt=false;loginTimeout=30;
    username: UniversitySA           #spring.datasource.username=sa
    password: 1university@SECRET!    #spring.datasource.password=Admin1234

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        proc:
          param_null_passing: true
        jdbc:
          fetch_size: 100
          batch_size: 50
          batch_versioned_data: true
          lob:
            non_contextual_creation: true

eureka:
  client:
    # This is eureka client
    register-with-eureka: true
    fetch-registry: true
    # Register url to the server
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost

security:
  jwt:
    secret: absolutelySecret
    expire: 900000

logging.level.root: info