# HTTP Server
server.port: 8081   # HTTP port

# Spring properties
spring:
  application:
    name: university-eureka-server

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
