server:
  port: 8080

spring:
  application:
    name: university-server

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=university;encrypt=false;loginTimeout=30;
    username: UniversitySA           #spring.datasource.username=sa
    password: 1university@SECRET!    #spring.datasource.password=Admin1234

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        proc:
          param_null_passing: true
        jdbc:
          fetch_size: 100
          batch_size: 50
          batch_versioned_data: true
          lob:
            non_contextual_creation: true

security:
  jwt:
    secret: absolutelySecret
    expire: 900000

logging.level.root: info